openapi: 3.0.1

info:
  title: ValkyrAI CORE API

  description: The API for accessing ValkyrAI services
  termsOfService: https://valkyrlabs.com/tos/
  contact:
    email: info@valkyrlabs.com
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  version: 0.9.25

externalDocs:
  description: Learn more about ValkyrAI
  url: https://valkyrlabs.com/vai/docs

servers:
  - url: http://localhost:8080/v1
    description: local server (uses live data)
  - url: https://valkyrlabs.com/v1
    description: production server

tags:

paths:

## Valkyr LABS API
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: The unique identifier of the object to retrieve.
      schema:
        type: string
        format: uuid

  schemas:
    
    ## DEMO GAME
    Game:
    Weapon:
    Level:
    Attack:
    
    
## Practical Magic

    ## SecureField KMS - the ultimate encryption solution
    SecureKey:

    ## HeimdaLLM Service
    ## HeimdaLLM is responsible for intelligently managing ThorAPI
    ## HeimdaLLM is a function of the ValkyrAI Service

    # the ability to evolve APIs
    
    ## VALKYRAI AI Powered BPM
    # AI Worfklows + ThorAPI + HeimdaLLM
    Workflow:
    WorkflowState:
    Task:
    ExecModule:
    EventLog:
    IntegrationAccount:

    LlmDetails:

    Application:

    ## CMS
    ContentData:
    ContentMediaLink:
    
    ## Ratings
    Rating:

    ## Sage chat
    ChatMessage:
    ChatResponse:

    ## Basic Section
    Principal:
    Organization:
    Address:

    ## THORAPI
    Role:
    AclEntry:
    Login:
    Logout:

    ## CRM SECTION
    Customer:
    Opportunity:
    SalesActivity:
    SalesPipeline:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

    thorapi_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://{username}.valkyrlabs.com:{port}/oauth
          scopes:
            write:items: modify owned items
            read:items: read owned items

    api_key:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://valkyrlabs.com/auth
          scopes: {}
